# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: valinet
description: Engineering and hacking
seo_paginator_message: "%<current>s / %<total>s | "
name: Valentin Radu
author: Valentin Radu
email: valentingabrielradu@gmail.com
legal: '&copy; 2006-2024 VALINET Solutions SRL. All rights reserved.'
description_long: >- # this means to ignore newlines until "baseurl:"
  <em>Personal web space of <a href="/about">Valentin Radu</a>, mainly talking about engineering and hacking. Also available at 
  valinet6l6tq6d5yohaa6gdsf2ho4qcqcxyj2nahp5kd4z7nsa6ycdqd.onion</em>
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://valinet.ro" # the base hostname & protocol for your site, e.g. http://example.com
github_username: valinet
header_pages:
  - about.md
paginate: 8
paginate_path: "/:num/"
show_excerpts: true
disqus:
  shortname: valinet
projects:
  limit: 7
  exclude:
    archived: false
    forks: true
    projects:
    - valinet.github.io
    - valinet
    # - repo-name

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-octicons
minima:
  skin: custom
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
